function info = make_info(name, bits, symbols, baseband, options)
%MAKE_INFO Build consistent metadata for transmit waveform generation.
info = struct('modulation', name, 'sampleRate', options.sampleRate, ...
    'carrierFrequency', options.carrierFrequency, 'symbolRate', options.symbolRate, ...
    'inputBits', bits, 'symbols', symbols, 'baseband', baseband, ...
    'options', options, 'durationSeconds', numel(baseband) / options.sampleRate);
end
